//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNETCSharp.ServicioWebSOAPOperaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServicioWebSOAPOperaciones.WSOperaciones")]
    public interface WSOperaciones {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/LoginRequest", ReplyAction="http://ws/WSOperaciones/LoginResponse")]
        ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse Login(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/LoginRequest", ReplyAction="http://ws/WSOperaciones/LoginResponse")]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse> LoginAsync(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/ProcesarPagoRequest", ReplyAction="http://ws/WSOperaciones/ProcesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse ProcesarPago(ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/ProcesarPagoRequest", ReplyAction="http://ws/WSOperaciones/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse> ProcesarPagoAsync(ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPago", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pago;
        
        public ProcesarPagoRequest() {
        }
        
        public ProcesarPagoRequest(int total, int pago) {
            this.total = total;
            this.pago = pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPagoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ProcesarPagoResponse() {
        }
        
        public ProcesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperacionesChannel : ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperacionesClient : System.ServiceModel.ClientBase<ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones>, ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones {
        
        public WSOperacionesClient() {
        }
        
        public WSOperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones.Login(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string usuario, string contrasena) {
            ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest inValue = new ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest();
            inValue.Body = new ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse retVal = ((ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse> ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones.LoginAsync(ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginResponse> LoginAsync(string usuario, string contrasena) {
            ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest inValue = new ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequest();
            inValue.Body = new ClienteNETCSharp.ServicioWebSOAPOperaciones.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones.ProcesarPago(ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPago(request);
        }
        
        public int ProcesarPago(int total, int pago) {
            ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest inValue = new ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse retVal = ((ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones)(this)).ProcesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse> ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones.ProcesarPagoAsync(ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoResponse> ProcesarPagoAsync(int total, int pago) {
            ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest inValue = new ClienteNETCSharp.ServicioWebSOAPOperaciones.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            return ((ClienteNETCSharp.ServicioWebSOAPOperaciones.WSOperaciones)(this)).ProcesarPagoAsync(inValue);
        }
    }
}
