//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNETCSharp.ServicioWebSOAPReceta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServicioWebSOAPReceta.WSReceta")]
    public interface WSReceta {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSReceta/listarIngredientesRequest", ReplyAction="http://ws/WSReceta/listarIngredientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse listarIngredientes(ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSReceta/listarIngredientesRequest", ReplyAction="http://ws/WSReceta/listarIngredientesResponse")]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse> listarIngredientesAsync(ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSReceta/buscarRecetaRequest", ReplyAction="http://ws/WSReceta/buscarRecetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse buscarReceta(ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSReceta/buscarRecetaRequest", ReplyAction="http://ws/WSReceta/buscarRecetaResponse")]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse> buscarRecetaAsync(ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientes", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarIngredientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receta;
        
        public listarIngredientesRequest() {
        }
        
        public listarIngredientesRequest(string receta) {
            this.receta = receta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarIngredientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public listarIngredientesResponse() {
        }
        
        public listarIngredientesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarReceta", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class buscarRecetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public buscarRecetaRequest() {
        }
        
        public buscarRecetaRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarRecetaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class buscarRecetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public buscarRecetaResponse() {
        }
        
        public buscarRecetaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRecetaChannel : ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRecetaClient : System.ServiceModel.ClientBase<ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta>, ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta {
        
        public WSRecetaClient() {
        }
        
        public WSRecetaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRecetaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRecetaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRecetaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta.listarIngredientes(ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest request) {
            return base.Channel.listarIngredientes(request);
        }
        
        public string[] listarIngredientes(string receta) {
            ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest inValue = new ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest();
            inValue.receta = receta;
            ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse retVal = ((ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta)(this)).listarIngredientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse> ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta.listarIngredientesAsync(ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest request) {
            return base.Channel.listarIngredientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesResponse> listarIngredientesAsync(string receta) {
            ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest inValue = new ClienteNETCSharp.ServicioWebSOAPReceta.listarIngredientesRequest();
            inValue.receta = receta;
            return ((ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta)(this)).listarIngredientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta.buscarReceta(ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest request) {
            return base.Channel.buscarReceta(request);
        }
        
        public string buscarReceta(string nombre) {
            ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest inValue = new ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest();
            inValue.nombre = nombre;
            ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse retVal = ((ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta)(this)).buscarReceta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse> ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta.buscarRecetaAsync(ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest request) {
            return base.Channel.buscarRecetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaResponse> buscarRecetaAsync(string nombre) {
            ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest inValue = new ClienteNETCSharp.ServicioWebSOAPReceta.buscarRecetaRequest();
            inValue.nombre = nombre;
            return ((ClienteNETCSharp.ServicioWebSOAPReceta.WSReceta)(this)).buscarRecetaAsync(inValue);
        }
    }
}
